services:
  frontend:
    extends:
      file: ../frontend/docker-compose.yml
      service: frontend
      
  postgres:
    extends:
      file: ../backend/docker-compose.yml
      service: postgres

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pg-admin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    networks:
      - pg-network

  backend:
    extends:
      file: ../backend/docker-compose.yml
      service: backend

networks:
  pg-network:

volumes:
  pg-data: